### ISSUE TITLE
Invalid command line Expected -option_name or --option_name, got '-' using gget muscle

### ISSUE THREAD

**Issue by emilyrkang** [pachterlab/gget#101]
### What happened?

When I try to execute gget muscle via command line or via python script I get the same error message:

Via command line:

`C:\Users\mypath > gget muscle fastas_test.txt`

Or via python script:
`file_name = "fastas_test.txt"
gget.muscle(file_name)
print(type(muscle_alignment))
print(muscle_alignment)`

I get the same error message:

"Fri Aug 18 15:52:58 2023 INFO MUSCLE compiled.
Fri Aug 18 15:52:58 2023 INFO MUSCLE aligning...

Invalid command line
Expected -option_name or --option_name, got '-'"

This is how my fasta file is formatted:

> >Sequence1
MKTITLECMAIKLLDHLSEKEEQVKQRAEGEVKPEALQEALEKALKETGGVTVTKH
VRWTDGLTCGQLIKTNHPDKPTRIYVCLRGTKAKIADGAILKEDVIEKSTLNKFDLRG
ELKIEEKLRHLHPENSQSGDYPEAQIADGSKEVTLRQTCPTGWYFLRLLVDKDDKSYIK
ALAEKAAAKKVGELFNRYERPDCTLAKLDYVRVQVNIDAGGVLAALDRAEAIYALGLKA
ETEDGVVKLAADDKAAAPKAASRDPKAAGRVSSDPGVDSDGRGAPGPDGVGDSDSEDIAD
SEDKK
>Sequence2
MSTQQIYTQVKVLQAMRHNGKLTLIIRATGGVVKLAADDKAAAPKAASRDPKAAGRVSS
DPGVDSDGRGAPGPDGVGDSDSEDIADSEDKK

### gget version

0.27.0

### Operating System (OS)

Windows

### User interface

Command-line

### Are you using a computer with an Apple M1 chip?

Not M1

### What is the exact command that was run?

```shell
gget muscle fastas_test.txt
```

### Which output/error did you get?

```shell
Fri Aug 18 15:52:36 2023 INFO MUSCLE compiled.
Fri Aug 18 15:52:36 2023 INFO MUSCLE aligning...


Invalid command line
Expected -option_name or --option_name, got '-'
```

**Comment by lauraluebbert** [comment]
Hi Emily, 

gget muscle expects files in fasta format (even if the file is a .txt file), so the sequence headers should start with ">". I suspect that this is causing the problem here.

I tried to reproduce your error (I am not getting the exact same error message which might be a Linux vs. Windows thing) and provide a fix in this Colab notebook:  
https://colab.research.google.com/drive/1Hk0ot5NNNyeQXCajEMcQYSwPkdQGmXJn?usp=sharing

**Comment by emilyrkang** [comment]
It works when I run it in google colab. But when I copy the following portions into a python script and execute it locally I get the same error message.


code:
`
import gget

title1 = ">Sequence1"
seq1 = "MKTITLECMAIKLLDHLSEKEEQVKQRAEGEVKPEALQEALEKALKETGGVTVTKHVRWTDGLTCGQLIKTNHPDKPTRIYVCLRGTKAKIADGAILKEDVIEKSTLNKFDLRGELKIEEKLRHLHPENSQSGDYPEAQIADGSKEVTLRQTCPTGWYFLRLLVDKDDKSYIKALAEKAAAKKVGELFNRYERPDCTLAKLDYVRVQVNIDAGGVLAALDRAEAIYALGLKAETEDGVVKLAADDKAAAPKAASRDPKAAGRVSSDPGVDSDGRGAPGPDGVGDSDSEDIADSEDKK"
title2 = ">Sequence2"
seq2 = "MSTQQIYTQVKVLQAMRHNGKLTLIIRATGGVVKLAADDKAAAPKAASRDPKAAGRVSSDPGVDSDGRGAPGPDGVGDSDSEDIADSEDKK"

with open("fastas_test_2.txt", "w") as fasta_file:
  fasta_file.write(title1 + "\n" + seq1 + "\n" + title2 + "\n" + seq2)

gget.muscle("fastas_test_2.txt")

`

error:


`

mypath> py gget_muscle_debug.py
Mon Aug 21 11:17:25 2023 INFO MUSCLE compiled.
Mon Aug 21 11:17:25 2023 INFO MUSCLE aligning...


Invalid command line
Expected -option_name or --option_name, got '-'


`

**Comment by lauraluebbert** [comment]
Is it possible that there is a "-" or spaces somewhere in the absolute path to your fasta file or muscle binary (inside gget)?

**Comment by emilyrkang** [comment]
I don't think so. The python script "gget_muscle_debug.py" and the fasta file generated by the script and then used in gget.muscle "fastas_test_2.txt" is all in the same folder.

**Comment by lauraluebbert** [comment]
Even if they are in the same folder, gget muscle will use the absolute path to these files from the root directory of your computer. For Linux and Darwin, we can just put the paths in quotation marks and then there are no problems with spaces etc, but for Windows, this does not work unfortunately (this all happens under the hood in gget muscle).

**Comment by emilyrkang** [comment]
That was it, thanks!
