### ISSUE TITLE
Multiple sequence alignment for multiple species

### ISSUE THREAD

**Issue by mini374** [pachterlab/gget#104]
### What happened?

We want to use gget.muscle for multiple sequence alignments for multiple species. These multiple species have different length ensembl_id/gene_names. Therefore, they start at different places on the page.

### gget version

I import gget into Google CoLab each time I run my analysis. For this example it is only minimal in other cases it can be more severe depending on the species.

[gget.muscle.docx](https://github.com/pachterlab/gget/files/12738645/gget.muscle.docx)

### Operating System (OS)

Windows, Other (please specify above)

### User interface

Google Colab (please include a shareable link above)

### Are you using a computer with an Apple M1 chip?

Not M1

### What is the exact command that was run?

```shell
!pip install --upgrade gget
import gget
gget.search
gget.seq
gget.muscle
```

**Comment by lauraluebbert** [comment]
Hi, thank you for your question. To solve this issue, I would suggest generating a .afa file using the `save=True` argument (also see https://pachterlab.github.io/gget/en/muscle.html). The generated .afa files can then be visualized with alignment viewers like Belvu or [alv](https://github.com/arvestad/alv). Let me know if this works, I'll also work on a solution to fix this problem in the gget muscle output.

**Comment by lauraluebbert** [comment]
The current dev version of gget should be slightly more robust to this issue (it will only work as long as the differences in the sequence names are not too large though). You can install it in Google Colab using the following command:
```
!pip install -q mysql-connector-python==8.0.29
!pip install -q git+https://github.com/pachterlab/gget.git@dev
```

Please give it a try and let me know if this is sufficient to fix your problem.

**Comment by mini374** [comment]
thanks for getting back to me on that issue. 
I am still having issues even though I tried both approaches.
In addition, we are working with a non traditional model organism as well I am afraid that that further complicates the matter.

**Comment by lauraluebbert** [comment]
Could you please send me a screenshot of what the output currently looks like or, if possible, a link to your Google Colab notebook and one example file?

**Comment by mini374** [comment]
Sure, this is the CoLab link: https://colab.research.google.com/drive/1M64Inu1ZbQOQksEv1Zmrvx1iMqPBANt-?usp=sharing.

And a screenshot of the output file is attached.

**Comment by lauraluebbert** [comment]
Could you also please send me one of the generated .ala files? I will try to find a program that can visualize these better

**Comment by mini374** [comment]
the file type is not supported i generated a text file
[CD86_HS-MM-XT-PW.fasta.txt](https://github.com/pachterlab/gget/files/12774368/CD86_HS-MM-XT-PW.fasta.txt)

**Comment by mini374** [comment]
I wanted to ask if there were any news about the gget code improvement?

**Comment by lauraluebbert** [comment]
Hi, in your Google Colab, because you installed and imported gget using the standard installation first, the notebook was actually not using the new version. Either way, I don't think my solution actually fixed your problem, so I think going with `alv` is the right solution. However, you need to pass `alv` the aligned fasta file returned by `gget.muscle` (not the original fasta file). Take a look at this notebook:

https://colab.research.google.com/drive/16vQOJPD5jCb6lbslPMJ-wOvG4j8Y0Lx3?usp=sharing

**Comment by mini374** [comment]
Thank you. It looks like I had hoped now.

**Comment by lauraluebbert** [comment]
Great, I'm glad this worked! :) I'll close this issue for now, but please don't hesitate to reach out if you run into any other issues.
