### ISSUE TITLE
Add module to depmap database

### ISSUE THREAD

**Issue by lauraluebbert** [pachterlab/gget#121]
### Request type

New module

### Request description

https://depmap.org/

**Comment by abearab** [comment]
Cool! Looking forward to this. I would like to use it in https://github.com/GilbertLabUCSF/CanDI.

**Comment by lauraluebbert** [comment]
Note: Some DepMap data will be accesible through [gget opentargets](https://pachterlab.github.io/gget/en/opentargets.html) in gget version >= 0.29.0
