### ISSUE TITLE
A couple CLI tweaks

### ISSUE THREAD

**Issue by mjsteinbaugh** [pachterlab/gget#16]
Hi @lauraluebbert ,

I noticed with gget 0.2.0 that `gget --help` returns with an error code. Also, it appears that `gget -v` or `gget --version` aren't currently working as expected.

Best,
Mike

**Comment by lauraluebbert** [comment]
Hi Michael, 

The cli bugs should be fixed in version 0.2.1 (`pip install --upgrade gget`). Thank you very much for bringing this to my attention! 

Best,

Laura
