### ISSUE TITLE
gget ref for non-vertebrate species

### ISSUE THREAD

**Issue by gonzalobenegas** [pachterlab/gget#25]
Hello,

Thank you for this awesome tool! I'd love to get ftp links for plant species available in [Ensembl Plants](https://plants.ensembl.org/index.html). Would this be possible with gget?

Thanks,
Gonzalo

**Comment by lauraluebbert** [comment]
Hi Gonzalo, 

Thank you for the feedback! I just implemented a connection to Ensembl Plants for gget ref. Just upgrade to the latest gget version (`pip install --upgrade gget`) and pass a plant species to gget ref (e.g. `gget ref zea_mays`). Please let me know if there are any issues! :) 

Best,

Laura

**Comment by gonzalobenegas** [comment]
Fantastic, thanks for the quick update!
