### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by lara-marinelli** [pachterlab/gget#26]
Running:
`gget.ref("mouse")`

I've got this 

> error:
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
ProtocolError                             Traceback (most recent call last)
ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
During handling of the above exception, another exception occurred:
ConnectionError                           Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/requests/adapters.py](https://localhost:8080/#) in send(self, request, stream, timeout, verify, cert, proxies)
 496 
 497         except (ProtocolError, socket.error) as err:
--> 498             raise ConnectionError(err, request=request)
499 
500         except MaxRetryError as e:

ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by lauraluebbert** [comment]
Hi Lara, 

This looks like the Ensembl server rejected the request, which happens sporadically. Please upgrade to the latest gget version (`pip install --upgrade gget`) and try again. Let me know if the issue persists.
