### ISSUE TITLE
gget alphafold "zsh: illegal hardware instruction"

### ISSUE THREAD

**Issue by alwhiteh** [pachterlab/gget#30]
Hello,

I'm trying to run gget alphafold on my M1 mac, but am encountering the following error:

`zsh: illegal hardware instruction`

I noticed other threads ([143](https://github.com/apple/tensorflow_macos/issues/143))  that comment on the difficulty of running tensorflow with m1 hardware and was wondering if this might be the issue?

I checked to see what version of tensorflow was installed with pip and found several tensorflow-related packages, but not tensorflow itself, I'm guessing this is why other workarounds don't work (i.e. installing tensorflow alpha, or what is suggested here: https://www.youtube.com/watch?v=WFIZn6titnc) :

tensorboard                   2.9.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow-cpu                2.9.1
tensorflow-estimator          2.9.0
tensorflow-io-gcs-filesystem  0.26.0

Is there an easy way to resolve this?

-Alex

**Comment by lauraluebbert** [comment]
Hi Alex, 

I don't see an issue with the tensorflow packages you sent. Could you please send me the command you ran? Did you try running `gget setup alphafold` first?

**Comment by mcsymbiont** [comment]
Hi Laura, 

I get the same error, on a MacBook Pro (14-inch, 2021) running OS 12.4. I did run `gget setup alphafold` first:

```
(base) jpmccutc@BIOD2009 ~ % gget alphafold MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK
zsh: illegal hardware instruction  gget alphafold 
(base) jpmccutc@BIOD2009 ~ %
```

Thanks, 

--John

**Comment by alwhiteh** [comment]
Hi Laura,

I did run gget setup alphafold first. The command I ran was: 

`gget alphafold MDDDIAALVVDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYVGDEAQSKRGILTLKYPIEHGIVTNWDDMEKIWHHTFYNELRVAPEEHPVLLTEAPLNPKANREKMTQIMFETFNTPAMYVAIQAVLSLYASGRTTGIVMDSGDGVTHTVPIYEGYALPHAILRLDLAGRDLTDYLMKILTERGYSFTTTAEREIVRDIKEKLCYVALDFEQEMATAASSSSLEKSYELPDGQVITIGNERFRCPEALFQPSFLGMESCGIHETTFNSIMKCDVDIRKDLYANTVLSGGTTMYPGIADRMQKEITALAPSTMKIKIIAPPERKYSVWIGGSILASLSTFQQMWISKQEYDESGPSIVHRKCF`

In the mean time I also tried installing tensorflow with the M1 mac specific instructions ( https://developer.apple.com/metal/tensorflow-plugin/) and reinstalling gget, but this yields another error:

```
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu (from alphafold) (from versions: none)
ERROR: No matching distribution found for tensorflow-cpu
Wed Aug 10 12:21:46 2022 ERROR AlphaFold installation failed.
```

Thanks for your help!

-Alex

**Comment by lauraluebbert** [comment]
Hi Alex and John, 

I am having trouble recreating your error. The package tensorflow should not be required to run gget alphafold (only tensorflow-cpu==2.5.0 is required). Could you please try again in a new environment? This works for me (on MacBook):

```bash
conda create -n alphafold python=3.9
conda activate alphafold
pip install -U gget
conda install -c conda-forge openmm=7.5.1
gget setup alphafold
gget alphafold MDDDIAALVVDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYVGDEAQSKRGILTLKYPIEHGIVTNWDDMEKIWHHTFYNELRVAPEEHPVLLTEAPLNPKANREKMTQIMFETFNTP
```

**Comment by mcsymbiont** [comment]
Thanks, Laura. Unfortunately I still get the same error.

**Comment by alwhiteh** [comment]
Same here. I also tried downgrading tensorflow-cpu to 2.5.0 and got the same result.

**Comment by lauraluebbert** [comment]
This is difficult for me to debug since I cannot reproduce the error (it seems M1 specific?). 

These recommendations might be worth giving a try: 
Some people recommend using Python version 3.8.5. (https://github.com/apple/tensorflow_macos/issues/143)

From https://www.pythonfixing.com/2021/11/fixed-illegal-hardware-instruction.html:
Seemed like my terminal app was running in Rosetta. This can be changed by right-clicking on the app -> get info -> disable "open with rosetta".

**Comment by mcsymbiont** [comment]
Hi Laura, 

I get it, thanks for trying! I am going to install gget on a linux machine, it does seem M1 specific. (I tried that Terminal app thing already, I had already disabled the "open with rosetta" box.) Thanks again.

**Comment by alwhiteh** [comment]
Likewise, thanks again!
