### ISSUE TITLE
Frozen terminal

### ISSUE THREAD

**Issue by lt11** [pachterlab/gget#34]
Dear developers,

I found minor issue running gget alphafold on macOS (11.6.5). My terminal went blocked after finishing "Jackhmmer search". It was unblocked by closing the window of the image reporting the "Non-Gap Count" vs "Per-Residue Count Of Non-Gap Amin Acids in the MSA For Sequence 1". Then it proceeded with "Running model_2".

Best,

Lorenzo

**Comment by lauraluebbert** [comment]
Hi Lorenzo,

Thank you for letting us know! That plot is created by the original AlphaFold Cola code which I try to modify as little as possible (hence this plot will always show, regardless of whether or not the plotting option is enabled). Interestingly, the plot simply doesn't show for me when I call gget alphafold from the terminal on my Mac and Linux. It's good to know this is not always the case. I'll try to find a better of handling it. Thanks again!

Best,

Laura
