### ISSUE TITLE
AlphaFold model parameters download error

### ISSUE THREAD

**Issue by EvoEpi** [pachterlab/gget#35]
Hi! I am hitting a SSL cert problem when running alphafold setup:

```
Tue Aug 16 10:18:49 2022 INFO Downloading AlphaFold model parameters (requires 4.1 GB of storage). This might take a few minutes.
curl: (60) SSL certificate problem: unable to get local issuer certificate                                                                                
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Where are the parameters being downloaded from? I believe this will help me check if I have the right certs and are in the right place. Any additional advice to solve this error would be greatly appreciated! Thank you!

**Comment by lauraluebbert** [comment]
The parameters are downloaded from https://storage.googleapis.com/alphafold/alphafold_params_colab_2022-03-02.tar into the gget/bins/alphafold/params/ folder inside the gget package folder (the 'params' folder might have to be created). If you manually download the parameters and add them to this folder, gget should be able to find them.

**Comment by EvoEpi** [comment]
Thank you! I was able to overcome this error by downloading the model parameters and moving them to gget/bins/alphafold/params/.

I am currently working through another error, and will post in a new issue if I cannot resolve.

Many thanks again!

**Comment by lauraluebbert** [comment]
Sounds good; in this case, I will close this issue for now. Please let me know if there are other issues!
