### ISSUE TITLE
Fails to depict and answer the polymeric forms

### ISSUE THREAD

**Issue by Harpreet525** [pachterlab/gget#36]
i have used gget to predict the structure of chloride dismutase and it successfully gave me the pdb file of the structure in a monomeric form and when i cross checked it with pdb database it showed the structure to be a hexameric protein.
Now is it necessary to fill this gap ?

**Comment by lauraluebbert** [comment]
Hi! It might be worth playing around with the mono- versus multimer function in gget alphafold. If you pass each sequence of the hexamer separately as a list (or in a .fa), the program will automatically use the multimer model. This will take much longer but might yield results closer to the expected structure.

**Comment by Harpreet525** [comment]
HiThe sequence is at 58% identity and is a homohexadimer. So i dont know how but the pdb database showed the same monomer arranged in a circular 6mer perimeter. Plus i cannot put same sequences 6 times, is it ?I mean prodigal captured only one sequenceRegardsHarpreet SinghOn Aug 17, 2022 12:22 AM, Laura Luebbert ***@***.***> wrote:
Hi! It might be worth playing around with the mono- versus multimer function in gget alphafold. If you pass each sequence of the hexamer separately as a list (or in a .fa), the program will automatically use the multimer model. This will take much longer but might yield results closer to the expected structure.

**Comment by Harpreet525** [comment]
i also happen to face an issue with supplying a fasta file to read as it returns an error that fasta file starts with '>' but myt file does contain the '>' symbol at the starting.

And i am plotting the pdb file separately in pymol, is the plotting function embedded in gget alphafold as i couldnt get any plot

**Comment by lauraluebbert** [comment]
Hi, I ran gget alphafold on a fasta file containing the chloride dismutase sequence (from PDB 2VHH) 6 times (pasted below). (Note: I had no problem inputting the fasta file. Please make sure your fasta is formatted correctly, starting with a single-line description without any characters/lines preceding the ">".) Inputting several sequences automatically uses the multimer model. The resulting prediction looks as follows:

<img width="791" alt="Screen Shot 2022-08-19 at 11 49 37 AM" src="https://user-images.githubusercontent.com/56094636/185687116-772e36fa-3511-4e4a-8328-aabc352f535c.png">

```
>1
GSHMQPMQAMKIERGTILTQPGVFGVFTMFKLRPDWNKVPAMERKGAAEEVKKLIEKHKDNVLVDLYLTRGLETNSDFFFRINAYDLAKAQTFMREFRSTTIGKNADVFETLVGVTKPLNYISKDKSPGLNAGLSSATYSGPAPRYVIVIPVKKNAEWWNMSPEERLKEMEVHTTPTLAYLVNVKRKLYHSTGLDDTDFITYFETDDLTAFNNLMLSLAQVKENKFHVRWGSPTTLGTIHSPEDVIKALAD
>2
GSHMQPMQAMKIERGTILTQPGVFGVFTMFKLRPDWNKVPAMERKGAAEEVKKLIEKHKDNVLVDLYLTRGLETNSDFFFRINAYDLAKAQTFMREFRSTTIGKNADVFETLVGVTKPLNYISKDKSPGLNAGLSSATYSGPAPRYVIVIPVKKNAEWWNMSPEERLKEMEVHTTPTLAYLVNVKRKLYHSTGLDDTDFITYFETDDLTAFNNLMLSLAQVKENKFHVRWGSPTTLGTIHSPEDVIKALAD
>3
GSHMQPMQAMKIERGTILTQPGVFGVFTMFKLRPDWNKVPAMERKGAAEEVKKLIEKHKDNVLVDLYLTRGLETNSDFFFRINAYDLAKAQTFMREFRSTTIGKNADVFETLVGVTKPLNYISKDKSPGLNAGLSSATYSGPAPRYVIVIPVKKNAEWWNMSPEERLKEMEVHTTPTLAYLVNVKRKLYHSTGLDDTDFITYFETDDLTAFNNLMLSLAQVKENKFHVRWGSPTTLGTIHSPEDVIKALAD
>4
GSHMQPMQAMKIERGTILTQPGVFGVFTMFKLRPDWNKVPAMERKGAAEEVKKLIEKHKDNVLVDLYLTRGLETNSDFFFRINAYDLAKAQTFMREFRSTTIGKNADVFETLVGVTKPLNYISKDKSPGLNAGLSSATYSGPAPRYVIVIPVKKNAEWWNMSPEERLKEMEVHTTPTLAYLVNVKRKLYHSTGLDDTDFITYFETDDLTAFNNLMLSLAQVKENKFHVRWGSPTTLGTIHSPEDVIKALAD
>5
GSHMQPMQAMKIERGTILTQPGVFGVFTMFKLRPDWNKVPAMERKGAAEEVKKLIEKHKDNVLVDLYLTRGLETNSDFFFRINAYDLAKAQTFMREFRSTTIGKNADVFETLVGVTKPLNYISKDKSPGLNAGLSSATYSGPAPRYVIVIPVKKNAEWWNMSPEERLKEMEVHTTPTLAYLVNVKRKLYHSTGLDDTDFITYFETDDLTAFNNLMLSLAQVKENKFHVRWGSPTTLGTIHSPEDVIKALAD
>6
GSHMQPMQAMKIERGTILTQPGVFGVFTMFKLRPDWNKVPAMERKGAAEEVKKLIEKHKDNVLVDLYLTRGLETNSDFFFRINAYDLAKAQTFMREFRSTTIGKNADVFETLVGVTKPLNYISKDKSPGLNAGLSSATYSGPAPRYVIVIPVKKNAEWWNMSPEERLKEMEVHTTPTLAYLVNVKRKLYHSTGLDDTDFITYFETDDLTAFNNLMLSLAQVKENKFHVRWGSPTTLGTIHSPEDVIKALAD
```
