### ISSUE TITLE
openmm=7.5.1 is no longer available from conda-forge.

### ISSUE THREAD

**Issue by ahwchemistry** [pachterlab/gget#37]
I cannot get the Alphafold module to work, as openmm v.7.5.1 is no longer available from conda-forge. Later versions of openmm do not have the __version__ method, causing gget to crash using later versions.

**Comment by utimcraig** [comment]
In collab this is also a problem, additionally there's no conda in collab 
![image](https://user-images.githubusercontent.com/32027355/186442879-722d382b-354d-43d7-87da-92060a1e8cae.png)

**Comment by lauraluebbert** [comment]
Hi, thank you for bringing this issue to my attention! I inherited the annoying requirement for this specific openmm version directly from alphafold. I believe they are working on updating their code to the latest openmm version. In the meantime, please install openmm using command `conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1 `. For Colab, see [this notebook](https://colab.research.google.com/github/pachterlab/gget_examples/blob/main/gget_alphafold.ipynb).
