### ISSUE TITLE
pdb module

### ISSUE THREAD

**Issue by sbliven** [pachterlab/gget#38]
I love the new alphafold feature! Could there also be a `gget pdb` command for fetching structures from PDB? Combined with `gget blast -db pdbaa` this could be very powerful for comparing predictions and templates.

**Comment by lauraluebbert** [comment]
Thank you! Great idea! You are also not the first person to request a gget pdb module. It is on my to-do list (or happy to receive PRs if anybody wants to give it a try). 😊

**Comment by lauraluebbert** [comment]
Done! You can install `gget pdb` by updating to the latest gget version (`pip install -U gget`) (see the [ReadMe](https://github.com/pachterlab/gget/blob/main/README.md) for a full manual). `gget pdb` currently only takes PDB IDs as input. However, in the new version, `gget info` returns all PDB IDs associated with a given Ensembl ID. Please let me know your thoughts! Also, did you already have a use case in mind? If so, would you be willing to share it with me so I can use it as an example (with credit) (e.g. could you show me how you would use gget to compare predictions)?
