### ISSUE TITLE
Keyerror: "0000:query"

### ISSUE THREAD

**Issue by sharzil1994** [pachterlab/gget#41]
i have used example sequence in the alphafold module and it works fine however when I give it a custom sequence it give the said error
Keyerror: "0000:query". 
Please can you guide regarding the matter

**Comment by lauraluebbert** [comment]
Hi, thanks for using gget and for reaching out. Which gget version are you using? Could you please send me your exact command (including the sequence)?

**Comment by sharzil1994** [comment]
thank you for your response.
- I used the given command to install package around two weeks prior
pip install --upgrade gget 
- however i can't seem to find the installed version
-I used the given example that worked fine that is
import gget
gget.setup("alphafold") # setup only needs to be run once
gget.alphafold("MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK")
- however it gives issue when is use
gget.alphafold("MVKVFLVDDHEVVRRGLVDLLGADPELDVVGEAGSVAEAMARVPAARPDVAVLDVRLPDGNGIELCRDLLSRMPDLRCLILTSYTSDEAMLDAILAGASGYVVKDIKGMELARAVKDVGAGRSLLDNRAAAALMAKLRGAAEKQDPLSGLTDQERTLLGLLSEGLTNKQIADRMFLAEKTVKNYVSRLLAKLGMERRTQAAVFATELKRSRPPGDGP")

-the error is

KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_10534/2425348286.py in <module>
      1 import gget
----> 2 gget.alphafold("MVKVFLVDDHEVVRRGLVDLLGADPELDVVGEAGSVAEAMARVPAARPDVAVLDVRLPDGNGIELCRDLLSRMPDLRCLILTSYTSDEAMLDAILAGASGYVVKDIKGMELARAVKDVGAGRSLLDNRAAAALMAKLRGAAEKQDPLSGLTDQERTLLGLLSEGLTNKQIADRMFLAEKTVKNYVSRLLAKLGMERRTQAAVFATELKRSRPPGDGP")

~/anaconda3/envs/openmm/lib/python3.7/site-packages/gget/gget_alphafold.py in alphafold(sequence, out, relax, plot, show_sidechains)
    485         for db_name, db_results in raw_msa_results.items():
    486             merged_msa = notebook_utils.merge_chunked_msa(
--> 487                 results=db_results, max_hits=MAX_HITS.get(db_name)
    488             )
    489             if merged_msa.sequences and db_name != "uniprot":

~/anaconda3/envs/openmm/lib/python3.7/site-packages/alphafold/notebooks/notebook_utils.py in merge_chunked_msa(results, max_hits)
    105     e_values_dict = parsers.parse_e_values_from_tblout(chunk['tbl'])
    106     # Jackhmmer lists sequences as <sequence name>/<residue from>-<residue to>.
--> 107     e_values = [e_values_dict[t.partition('/')[0]] for t in msa.descriptions]
    108     chunk_results = zip(
    109         msa.sequences, msa.deletion_matrix, msa.descriptions, e_values)

~/anaconda3/envs/openmm/lib/python3.7/site-packages/alphafold/notebooks/notebook_utils.py in <listcomp>(.0)
    105     e_values_dict = parsers.parse_e_values_from_tblout(chunk['tbl'])
    106     # Jackhmmer lists sequences as <sequence name>/<residue from>-<residue to>.
--> 107     e_values = [e_values_dict[t.partition('/')[0]] for t in msa.descriptions]
    108     chunk_results = zip(
    109         msa.sequences, msa.deletion_matrix, msa.descriptions, e_values)

KeyError: '0000|query'

**Comment by sharzil1994** [comment]
![issue 0000 query](https://user-images.githubusercontent.com/51935396/188791221-b536f935-c747-49f1-afb8-f3a8059ef9ac.PNG)

**Comment by lauraluebbert** [comment]
Oddly, the same error occurs when plugging this sequence into the original Alphafold Colab and hence it is not a problem with the gget implementation. I’ll let them know and continue to trouble-shoot.

**Comment by sharzil1994** [comment]
thank you.
