### ISSUE TITLE
Error detecting openmm 

### ISSUE THREAD

**Issue by LalitNM** [pachterlab/gget#44]
Hi, as the title says, I tried to run this and installed all the dependencies. But, still, somehow it doesn't detect openmm. Can this be resolved? A screenshot is attached. Thanks. 

![image](https://user-images.githubusercontent.com/63332774/191033529-b1847e72-ac53-4de8-af6d-0662007051f7.png)

**Comment by lauraluebbert** [comment]
Hi, thanks for reaching out. Please update to the latest gget version (`pip install -U gget`; you can check the version with `gget -v`) and install openmm as follows: `conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1`. (Recommendation: Follow with `conda update -qy conda` to update conda to the latest version afterwards.) Do you still get the same error? Which OS are you using?

**Comment by LalitNM** [comment]
So, I ran the following commands in order:
1. `conda update -qy conda`
2. `conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1`
3. `pip install -U gget`

All commands ran successfully. And then I got a different error. It says to re-run a command which I already executed successfully.

![image](https://user-images.githubusercontent.com/63332774/191037023-11941731-0560-4dcb-bb45-68fcb35f6396.png)

PS: The gget is at its latest release (0.3.11)

**Comment by lauraluebbert** [comment]
Do you get the same error when running `gget setup alphafold` in the terminal directly (without calling Python)?

**Comment by lauraluebbert** [comment]
Could you please show me what `conda list | grep openmm` returns for you?

**Comment by LalitNM** [comment]
Here is the output.

![image](https://user-images.githubusercontent.com/63332774/191042914-f969771e-78d4-4334-963f-02d44323a5cc.png)

**Comment by lauraluebbert** [comment]
This is very odd, I have not encountered this error before. Could you please try to run the following in python: `import simtk.openmm as openmm` and then `openmm.__version__`. Does this work and does it output version 7.5.1?

**Comment by LalitNM** [comment]
`simtk` was not installed. So, I installed it and then tried to get version of `openmm`, but it says that the module is not found. Is this a problem with `simtk`?

![image](https://user-images.githubusercontent.com/63332774/191045100-45a4c1a2-dce5-47f4-af6a-ac284983dfb6.png)

**Comment by lauraluebbert** [comment]
It should not be necessary to install simtk separately. Maybe try removing both simtk and openmm and then reinstalling openmm as described above?

**Comment by LalitNM** [comment]
Still getting the same issue.

![image](https://user-images.githubusercontent.com/63332774/191060529-3cd46c62-69f5-403c-99dc-66f2bbd32818.png)
![image](https://user-images.githubusercontent.com/63332774/191060573-0daccc14-bfc1-498f-890b-b1364a8eae0c.png)
![image](https://user-images.githubusercontent.com/63332774/191060629-859e17ca-7b03-4e12-989d-7f60efed72a7.png)

**Comment by lauraluebbert** [comment]
It might also be worth to reinstall in a fresh conda environment

**Comment by emilyrkang** [comment]
What was the fix here? I'm having the same problem. I'm using an AWS Linux 2 AMI. I freshly installed miniconda.

```
(base) [ec2-user@ip-10-0-0-200 gget_alpha_fold_testing]$ gget setup alphafold
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/gget/gget_setup.py", line 91, in setup
    import simtk.openmm as openmm
ModuleNotFoundError: No module named 'simtk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/gget", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/gget/main.py", line 1518, in main
    setup(args.module)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/gget/gget_setup.py", line 108, in setup
    """
ImportError:
                Please install AlphaFold third-party dependency openmm v7.5.1 by running the following command from the command line:
                'conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1'
                (Recommendation: Follow with 'conda update -qy conda' to update conda to the latest version afterwards.)

(base) [ec2-user@ip-10-0-0-200 gget_alpha_fold_testing]$ conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/ec2-user/miniconda3

  added / updated specs:
    - conda==4.13.0


The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2022.12.~ --> pkgs/main::ca-certificates-2022.10.11-h06a4308_0
  certifi            conda-forge/noarch::certifi-2022.12.7~ --> pkgs/main/linux-64::certifi-2022.9.24-py37h06a4308_0
  conda              conda-forge::conda-4.14.0-py37h89c186~ --> pkgs/main::conda-4.13.0-py37h06a4308_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/ec2-user/miniconda3

  added / updated specs:
    - openmm=7.5.1


The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2022.10.11~ --> conda-forge::ca-certificates-2022.12.7-ha878542_0
  certifi            pkgs/main/linux-64::certifi-2022.9.24~ --> conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0
  conda              pkgs/main::conda-4.13.0-py37h06a4308_0 --> conda-forge::conda-4.14.0-py37h89c1867_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
(base) [ec2-user@ip-10-0-0-200 gget_alpha_fold_testing]$ conda update -qy conda
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/ec2-user/miniconda3

  added / updated specs:
    - conda


The following packages will be REMOVED:

  ruamel_yaml-0.15.100-py37h27cfd23_0
  yaml-0.2.5-h7b6447c_0

The following packages will be UPDATED:

  conda              conda-forge::conda-4.14.0-py37h89c186~ --> pkgs/main::conda-22.11.1-py37h06a4308_4

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2022.12.~ --> pkgs/main::ca-certificates-2022.10.11-h06a4308_0
  certifi            conda-forge/noarch::certifi-2022.12.7~ --> pkgs/main/linux-64::certifi-2022.9.24-py37h06a4308_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Retrieving notices: ...working... done
(base) [ec2-user@ip-10-0-0-200 gget_alpha_fold_testing]$ gget setup alphafold
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/gget/gget_setup.py", line 91, in setup
    import simtk.openmm as openmm
ModuleNotFoundError: No module named 'simtk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/gget", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/gget/main.py", line 1518, in main
    setup(args.module)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/gget/gget_setup.py", line 108, in setup
    """
ImportError:
                Please install AlphaFold third-party dependency openmm v7.5.1 by running the following command from the command line:
                'conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1'
                (Recommendation: Follow with 'conda update -qy conda' to update conda to the latest version afterwards.)

(base) [ec2-user@ip-10-0-0-200 gget_alpha_fold_testing]$

```

**Comment by lauraluebbert** [comment]
I haven't been able to reproduce this error on my Linux machine. I am eagerly awaiting the [openmm pipy version](https://github.com/openmm/openmm/issues/3796), and for AlphaFold to update to a newer openmm version requirement, which will hopefully solve all of the openmm installation problems. 

Could you please update to Python 3.8 and try again? That fixed the issue for the [Colab notebook](https://colab.research.google.com/github/pachterlab/gget_examples/blob/main/gget_alphafold.ipynb). Please also make sure it is added to your path.
