### ISSUE TITLE
Jupyter Notebook Kernel Dies When Using gget alphafold

### ISSUE THREAD

**Issue by tmileur** [pachterlab/gget#46]
I am able to use every gget module except for the alphaFold module. Whenever I implement a command line with AlphaFold the Jupyter Notebook kernel dies almost immediately. Is this something that occurs for others? Any recommendations are appreciated. 

# Generate new prediction from amino acid sequence
import gget
gget.setup("alphafold")
gget.alphafold("MAAHKGAEH")

<img width="628" alt="Screen Shot 2022-10-27 at 10 17 39 AM" src="https://user-images.githubusercontent.com/116834880/198359218-075a230d-45ee-4927-b726-a0db6c5cfe1f.png">

**Comment by lauraluebbert** [comment]
Hi! Thanks for reaching out. I have not encountered this problem before. Could you please give me some more info, e.g. which OS you are using and at which stage of the modeling the kernel dies? Do you get any sort of output/progress report/error message?

While we're figuring this out, you can also use gget alphafold via [Google Colab](https://colab.research.google.com/github/pachterlab/gget_examples/blob/main/gget_alphafold.ipynb).

**Comment by tmileur** [comment]
Hi Laura,

This issue seems related to my M1 - Mac. I notice that others are having a similar issue when using gget from the terminal. Sorry for the redundancy in issue. 

Regards,

Trevor

**Comment by lauraluebbert** [comment]
Hi Trevor, 

Ah yes, unfortunately, I have not found a solution for the M1 problem yet. I will close this issue for now since I don't think it is something I can solve on my end and refer to the previous discussion here: https://github.com/pachterlab/gget/issues/30#issuecomment-1212339957
Sorry I couldn't be more helpful.

Best,

Laura
