### ISSUE TITLE
Change gget search url to useast Ensembl mirror

### ISSUE THREAD

**Issue by lauraluebbert** [pachterlab/gget#61]
### What happened?

uswest.ensembl.org was discontinued. Change URLs returned by gget search to useast.ensembl.org

### gget version

NA

### Operating System (OS)

Not applicable

### User interface

Not applicable

### Are you using a computer with an Apple M1 chip?

Not applicable

**Comment by KevinDuringWork** [comment]
Is it worthwhile to parameterize the ensembl mirror with a default option of useast.ensembl.org? 

`time gget info ENSG00000012048

real	2m18.726s
user	0m2.123s
sys	0m0.236s
`

**Comment by lauraluebbert** [comment]
Hi Kevin, the speed problem with gget info has to do with the PDBe API. The next gget version v0.27.3 will include an option to turn PDB information on/off which should fix this issue.
