### ISSUE TITLE
Speeding up gget.info by making pdb search mutable

### ISSUE THREAD

**Issue by mmattano** [pachterlab/gget#63]
### Request type

Extension of existing module

### Request description

Dear Devs,
Hi! I really like this package, it’s a great project, but I ran into an issue when I added it to a workflow; I need to process a large number of Ensembl IDs so get.info would be the perfect fit for that but it takes a rather long time for mouse Ensembl IDs and it seems like that’s entirely due to the PDB API (which in my case, currently with mouse IDs, only returns NaNs). Would it be possible to make the PDB search mutable? I’m currently doing in that in a modified version of this function and like that it takes 5 s rather than 2.5 min per call.
Best,
Matthias

### Example command

```shell
gget.info('ENSexampleID', pdb=False)
```

### Example return value

Same as usual but without PDB entry (or NaN instead of an entry)

**Comment by lauraluebbert** [comment]
Hi Matthias,

Thanks for reaching out. Yes, this functionality already exists and I implemented it for the exact reason you’re mentioning. Just add the argument `ensembl_only=True`. Let me know if that gets the desired results. 

Best,

Laura

**Comment by mmattano** [comment]
Hi Laura,

Thanks for the swift reply! I do need the additional information (like UniProt ID, NCBI gene ID, etc), that's why I'm not limiting it to ensembl only and gget.info is quite convenient to get it all in one go. My modified version of the function work well for this specific application, so it's ok for me to keep using that, just wanted to pitch this modification in case other people run into the same issue.

Best,
Matthias

**Comment by lauraluebbert** [comment]
You’re right, I think the best would be to rewrite gget info so each database can be turned off individually (except for Ensembl). I’ll work on that for the next release. Thank you!

**Comment by mmattano** [comment]
Cool, thanks Laura!

**Comment by lauraluebbert** [comment]
There seems to be a speed problem with the specific PDBe API endpoint I am using for `gget info`. It's a relatively new endpoint and they are working on it, so I added the `pdb` flag to gget info and for now muted the output by default for gget version 0.3.27. Thanks again! :)
