### ISSUE TITLE
Option to reduce verbosity or turn off logging

### ISSUE THREAD

**Issue by gouinK** [pachterlab/gget#65]
### Request type

Extension of existing module

### Request description

This is a really useful easy-to-use package. I have been using this for relatively large requests and I was wondering if there is a way to reduce the verbosity of the logging info or turn off the logging completely?

**Comment by lauraluebbert** [comment]
Hi Kenny, thanks for reaching out! Which module(s) are you using? 

`gget info` and `gget blast` have a `-q / --quiet` (Python: `verbose=False`) argument that mutes the info level logging. The logging of all gget modules is handled using the package [logging](https://docs.python.org/3/library/logging.html). I agree we should add a `quiet` argument to all modules in future releases. In the meantime, you could try something like this when using gget in a Python environment:

```
import logging
logger = logging.getLogger('gget')
logger.setLevel(level=logging.WARNING)
```

**Comment by gouinK** [comment]
Sorry for the second message, even with the below code I still get an INFO message

```
import logging
import gget
logging.getLogger('gget').setLevel(level=logging.WARNING)
gget.seq('ENSE00001549666')
```
Output:
```
Mon Mar 20 17:29:10 2023 INFO Requesting nucleotide sequence of ENSE00001549666 from Ensembl.
['>ENSE00001549666 chromosome:GRCh38:1:26361634:26362022:-1',
 'GTGTGCCACAAGCGCTTCAGCAGCTCCAGTAACCTCAAGACCCACCTGCGCCTGCACTCCGGGGCCCGGCCCTTCCAGTGCAGTGTCTGCCGGAGTCGCTTCACCCAGCACATCCACCTGAAGCTGCACCATCGGCTGCATGCCCCACAGCCCTGTGGCCTGGTGCACACCCAGCTGCCCCTGGCCTCTCTGGCCTGCCTTGCCCAATGGCACCAGGGGGCACTAGATCTTATGGCGGTGGCATCTGAGAAACACATGGGCTATGACATAGATGAGGTCAAAGTGTCCTCGACATCCCAGGGGAAAGCAAGAGCAGTGAGCCTGAGCAGTGCCGGGACTCCCCTGGTGATGGGGCAGGACCAGAACAATTAAAAATGTTTCTTCTGTCA']
```

**Comment by anhchi172** [comment]
Hi Kenny,

We are sorry that the logger solution did not work. The next gget version (0.27.5) will support reducing verbosity with an added argument `-q / --quiet` (Python: `verbose=False`) for all modules. You can already install this version from the dev branch using `pip install git+https://github.com/pachterlab/gget.git@dev`. Please be aware that this branch is still actively under development.
