### ISSUE TITLE
export plot as svg

### ISSUE THREAD

**Issue by nahid18** [pachterlab/gget#7]
is there any way to export the generated plots as svg?

**Comment by lauraluebbert** [comment]
Yes! You can save the plt object as you wish after calling the Enrichr plot. Here is an example:

```python
import matplotlib.pyplot as plt

enrichr_df = gget.enrichr(["CYP2J2", 
                           "PRDM8", 
                           "HHATL",
                           "GNB3", 
                           "EDIL3",
                           "TRPM1",
                           "CXCL14",
                           "CPLX3",
                           "CALM1",
                           "CCDC112", 
                           "SYNE1",
                           "CA8",
                           "H2AC20",
                           "ATP6V1H",
                           "RGS16",
                           "TSHB",
                           "CCDC136",
                           "PCP2"], 
                          database="celltypes", 
                          plot=True)

plt.savefig("enrichr_plot.svg", dpi=300, bbox_inches="tight")
```

**Comment by nahid18** [comment]
awesome! thank you!

**Comment by nahid18** [comment]
The code example doesn't seem to work @lauraluebbert

**Comment by lauraluebbert** [comment]
Could you send me a screenshot of your error?

**Comment by nahid18** [comment]
The error is that it produces a white svg instead of the generated figure. 

About vereion, I ran the code on google colab notebook and installed gget via pip, so the latest pip package.

**Comment by lauraluebbert** [comment]
This works for me and returns the SVG shown below. Are you sure that your query returns results? If no matches were found, the plot will be empty.

https://colab.research.google.com/drive/1IcKnG1EWcQsGodB_uuZPaVm10UfvQoft?usp=sharing

![enrichr_plot](https://user-images.githubusercontent.com/56094636/170839385-da17229d-4dea-4721-8993-4690fff98fe9.svg)

**Comment by nahid18** [comment]
This works as expected. Thanks!

I understand what was my mistake now. I was generating two figures at the same time and was running the `savefig` command at a different code block.
