### ISSUE TITLE
cellxgene filter improvements

### ISSUE THREAD

**Issue by atolopko-czi** [pachterlab/gget#78]
### Request type

Extension of existing module

### Request description

The [`gget_cellxgene`](https://github.com/pachterlab/gget/blob/dev/gget/gget_cellxgene.py) module could support additional filtering options, providing the full set of [metadata attributes that are available in the Census](https://github.com/chanzuckerberg/cellxgene-census/blob/main/docs/cellxgene_census_schema.md#cell-metadata--census_objcensus_dataorganismobs--somadataframe). In particular, supporting `is_primary_data` will allow users to ignore cells that are duplicated across multiple CELLxGENE datasets. See https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#is_primary_data. It would be reasonable to have a default value of `True` for this attribute.

Also, the current defaults will attempt to load the entire Census into an AnnData object, which requires a considerable amount of RAM (100's GBs) and high network bandwidth. You might consider enforcing that at least one obs filter is specified or a subset of genes is specified.

**Comment by lauraluebbert** [comment]
Hi Andrew, thank you very much for your suggestions! 

I updated the module to include the complete set of metadata attributes. 

I wanted to give users as much freedom as possible, so I didn't enforce a filter. However, I added a warning when a user calls the current defaults without specifying metadata filters with instructions on how to add them. 

Please let me know if you have any further thoughts or comments!
