### ISSUE TITLE
Specify version in ensembl "search" module

### ISSUE THREAD

**Issue by KleinSamuel** [pachterlab/gget#89]
### Request type

Extension of existing module

### Request description

Hi,
I would like to have the option to specify a version of the queried ensembl database when searching with the "search" module.
As far as I can see, gget uses the most current version but I can see use-cases where one would like to query older versions also.

### Example command

```shell
gget search -s homo_sapiens -v 96 "ACE2"
```

**Comment by lauraluebbert** [comment]
Hi Samuel, 

Thank you for your suggestion! I added a `-r``--release` argument to the `gget species` module, which takes an Ensembl version number. This change will be part of the next release. You can already install the dev version like this:

`pip install git+https://github.com/pachterlab/gget.git@dev`

Please note that it is still actively under development. Let me know if there are any issues.

**Comment by KleinSamuel** [comment]
Thank you for the quick response!

I have used the development branch to test some of my use-cases and it seems to be working just fine.
