### ISSUE TITLE
Background for enrichr

### ISSUE THREAD

**Issue by gjhuizing** [pachterlab/gget#9]
Hi!
Would it be possible to specify a background set of genes for the `enrichr` function?
Best
GJ

**Comment by lauraluebbert** [comment]
Hi GJ, 

I am not sure I understand your request. Could you please describe how you would do this on the [Enrichr website](https://maayanlab.cloud/Enrichr/)?

Best,

Laura

**Comment by gjhuizing** [comment]
Hi! Thanks for the quick answer.

By background I mean the universe or statistical domain of reference. I'm no expert in GSEA but from what I understood it should in some cases be smaller than the whole genome (e.g. only the genes whose expression is detected in the experiment). See [1] at "remaining questions, section 4".

After searching a bit, it seems that Enrichr actually doesn't have that option. So feel free to mark this as solved :)

Maybe that is why Scanpy chose to have g:Profiler in their API https://biit.cs.ut.ee/gprofiler/gost ? There is an explanation on the statistical domain in section "Statistical domain scope" of https://biit.cs.ut.ee/gprofiler/page/docs.

Best
GJ

[1] Huang, Da Wei, Brad T. Sherman, and Richard A. Lempicki. "Bioinformatics enrichment tools: paths toward the comprehensive functional analysis of large gene lists." Nucleic acids research 37.1 (2009): 1-13.
